repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.4
    hooks:
      - id: ruff
        args: [--fix]
        exclude: ^experiments/
      - id: ruff-format
        exclude: ^experiments/
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.14.1
    hooks:
      - id: mypy
        args: [--ignore-missing-imports]
        exclude: ^experiments/
        pass_filenames: false
        entry: mypy headroom
